{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chartmuseum.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "chartmuseum.labels.standard" . | indent 4 }}
{{- end -}}
